server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: service_01
    static_configs:
      - targets:
          - localhost
        labels:
          job: service_01
          __path__: /var/log/app/service_01/*.log

  - job_name: service_02
    static_configs:
      - targets:
          - localhost
        labels:
          job: service_02
          __path__: /var/log/app/service_02/*.log

